Scenario: Network main information visual verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then user should be able to see the POKT Price. Example: US $0.08
    And user should be able to see the Total Staked Tokens. Example: 5,000,015,975
    And user should be able to see the Total Staked Nodes. Example: 5
    And user should be able to see the Total Staked Apps. Example: 1

Scenario: Network main information verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    And the descripbed main network information is present.
    Then execute the following GET call: Example: 
    |https://api-testnet.dashboard.pokt.network:4200/api/network/summary|
    And receive the following response, that should have all of the information displayed in the UI:
    {
        "poktPrice":"0.08",
        "totalStakedTokens":"5000015975000000",
        "totalStakedApps":"1",
        "totalStakedNodes":"5"
    }
    And each {poktPrice}, {totalStakedTokens}, {totalStakedApps}, {totalStakedNodes}, matches the information displayed in the UI.

Scenario: Registered Nodes visual verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then make sure to check the Registered Nodes list, being present.
    And scroll all the way doen the list.
    And notice that the Address, Name and status information are present. Example: 
    | 6925c38c9303a7a1864e9dfcc85b86f9c150519a | N/A | Staked|

Scenario: Registered Nodes verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then execute the following GET call: Example: 
    |https://api-testnet.dashboard.pokt.network:4200/api/nodes/?limit=10&offset=0|
    And receive the following response, that should have all of the information displayed in the UI:
    [
        {
            "name":"N/A",
            "address":"6925c38c9303a7a1864e9dfcc85b86f9c150519a",
            "status":2
        },
        {
            "name":"N/A",
            "address":"7674a47cc977326f1df6cb92c7b5a2ad36557ea2",
            "status":2
        },
        {
            "name":"N/A",
            "address":"77e608d8ae4cd7b812f122dc82537e79dd3565cb",
            "status":2
        },
        {
            "name":"N/A",
            "address":"c7b7b7665d20a7172d0c0aa58237e425f333560a",
            "status":2
        },
        {
            "name":"N/A",
            "address":"e6946760d9833f49da39aae9500537bef6f33a7a",
            "status":2
        }
    ]
    And each {name}, {address}, {status} matches the information displayed in the UI.

Scenario: Registered Nodes verification - pocket CLI side
    Given that the user is in the Pocket Dashboard and has the Pocket Core CLI running locally. Example: 
    |https://dashboard.testnet.pokt.network/dashboard| pocket start - in testnet/mainnet | 
    When the page is fully loaded.
    And the pocket CLI is synced at the current network's height.
    Then find the Registered Nodes table.
    And pick one node address.
    And execute via terminal, the following CLI command: "pocket query node <address>"
    Then response should be accurate and matching the information in the table, with status and node address matching. Example:
    {
        "address": "5bfe661adc7bd1ccc637c83ecf5eb3594ae3bed0",
        "chains": [
            "0002"
        ],
        "jailed": true,
        "public_key": "1a536e47a17ea2d41e4233884bb41cc8b181c0c686e8278c0d47547f2c97db0c",
        "service_url": "https://pocket1.pathrocknetwork.org:8082",
        "status": 2,
        "tokens": "199999400002",
        "unstaking_time": "0001-01-01T00:00:00Z"
    }

Scenario: Registered Apps visual verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then make sure to check the Registered Apps list, being present.
    And scroll all the way doen the list.
    And notice that the Address, Name and status information are present. Example: 
    | 6925c38c9303a7a1864e9dfcc85b86f9c150519a | N/A | Staked|

Scenario: Registered Apps verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then execute the following GET call: Example: 
    |https://api-testnet.dashboard.pokt.network:4200/api/applications/?limit=10&offset=0|
    And receive the following response, that should have all of the information displayed in the UI:
    [
        {
            "name":"N/A",
            "address":"c80e0379869664e1f44300e95bc32c4975e8ae92",
            "status":2
        }
    ]
    And each {name}, {address}, {status} matches the information displayed in the UI.

Scenario: Supported Blockchains visual verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then make sure to check the Supported Blockchains list, being present.
    And scroll all the way doen the list.
    And notice that the Network, Network ID, Hash, Description, Ticket and Index information are present. Example: 
    | POKT-mainnet | mainnet | 0001|   | POKT | 1 |

Scenario: Supported Blockchains verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then execute the following GET call: Example: 
    |https://api-testnet.dashboard.pokt.network:4200/api/network/chains|
    And receive the following response, that should have all of the information displayed in the UI:
    [
        {
            "_id":"0001",
            "ticker":"POKT",
            "networkID":"mainnet",
            "network":"POKT-mainnet",
            "description":"",
            "index":1,
            "blockchain":"mainnet",
            "active":true
        },
        {
            "_id":"0002",
            "ticker":"POKT",
            "networkID":"testnet",
            "network":"POKT-testnet",
            "description":"",
            "index":2,
            "blockchain":"testnet",
            "active":true
        },
        {
            "_id":"0003",
            "ticker":"AION",
            "networkID":"32",
            "network":"AION-32",
            "description":"",
            "index":3,
            "blockchain":"aion-32",
            "active":true
        },
        {
            "_id":"0004",
            "ticker":"AION",
            "networkID":"256",
            "network":"AION-256",
            "description":"",
            "index":4,
            "blockchain":"aion-256",
            "active":true
        },
        {
            "_id":"0005",
            "ticker":"ALGO",
            "networkID":"mainnet-v1.0",
            "network":"ALGO-mainnet-v1.0",
            "description":"",
            "index":5,
            "blockchain":"algo-mainnet",
            "active":true
        },
        {
            "_id":"0006",
            "ticker":"ALGO",
            "networkID":"testnet-v1.0",
            "network":"ALGO-testnet-v1.0",
            "description":"",
            "index":6,
            "blockchain":"algo-testnet",
            "active":true
        },
        {
            "_id":"0007",
            "ticker":"ALGO",
            "networkID":"betanet-v1.0",
            "network":"ALGO-betanet-v1.0",
            "description":"",
            "index":7,
            "blockchain":"algo-betanet",
            "active":true
        },
        {
            "_id":"0008",
            "ticker":"ANT",
            "networkID":"mainnet",
            "network":"ANT-mainnet",
            "description":"",
            "index":8,
            "blockchain":"ant-mainnet",
            "active":true
        },
        {
            "_id":"0009",
            "ticker":"ANT",
            "networkID":"testnet",
            "network":"ANT-testnet",
            "description":"",
            "index":9,
            "blockchain":"ant-testnet",
            "active":true
        },
        {
            "_id":"000A",
            "ticker":"AR",
            "networkID":"mainnet",
            "network":"AR-mainnet",
            "description":"Arweave Mainnet",
            "index":10,
            "blockchain":"ar-mainnet",
            "active":true
        },
        {
            "_id":"000B",
            "ticker":"BCH",
            "networkID":"mainnet",
            "network":"BCH-mainnet",
            "description":"",
            "index":11,
            "blockchain":"bch-mainnet",
            "active":true
        },
        {
            "_id":"000C",
            "ticker":"BCH",
            "networkID":"testnet",
            "network":"BCH-testnet",
            "description":"",
            "index":12,
            "blockchain":"bch-testnet",
            "active":true
        },
        {
            "_id":"000D",
            "ticker":"BSV",
            "networkID":"mainnet",
            "network":"BSV-mainnet",
            "description":"Bitcoin SV",
            "index":13,
            "blockchain":"bsv-mainnet",
            "active":true
        },
        {
            "_id":"000E",
            "ticker":"BSV",
            "networkID":"testnet",
            "network":"BSV-testnet",
            "description":"",
            "index":14,
            "blockchain":"bsv-testnet",
            "active":true
        },
        {
            "_id":"000F",
            "ticker":"BSV",
            "networkID":"stn",
            "network":"BSV-stn",
            "description":"",
            "index":15,
            "blockchain":"bsv-stn",
            "active":true
        },
        {
            "_id":"0010",
            "ticker":"BTC",
            "networkID":"mainnet",
            "network":"BTC-mainnet",
            "description":"",
            "index":16,
            "blockchain":"btc-mainnet",
            "active":true
        },
        {
            "_id":"0011",
            "ticker":"BTC",
            "networkID":"testnet",
            "network":"BTC-testnet",
            "description":"",
            "index":17,
            "blockchain":"btc-testnet",
            "active":true
        },
        {
            "_id":"0012",
            "ticker":"BTG",
            "networkID":"testnet",
            "network":"BTG-testnet",
            "description":"",
            "index":18,
            "blockchain":"btg-testnet",
            "active":true
        },
        {
            "_id":"0013",
            "ticker":"BTG",
            "networkID":"mainnet",
            "network":"BTG-mainnet",
            "description":"",
            "index":19,
            "blockchain":"btg-mainnet",
            "active":true
        },
        {
            "_id":"0014",
            "ticker":"DAPS",
            "networkID":"mainnet",
            "network":"DAPS-mainnet",
            "description":"",
            "index":20,
            "blockchain":"daps-mainnet",
            "active":true
        },
        {
            "_id":"0015",
            "ticker":"DASH",
            "networkID":"testnet",
            "network":"DASH-testnet",
            "description":"",
            "index":21,
            "blockchain":"dash-testnet",
            "active":true
        },
        {
            "_id":"0016",
            "ticker":"DASH",
            "networkID":"mainnet",
            "network":"DASH-mainnet",
            "description":"",
            "index":22,
            "blockchain":"dash-mainnet",
            "active":true
        },
        {
            "_id":"0017",
            "ticker":"DGB",
            "networkID":"testnet",
            "network":"DGB-testnet",
            "description":"digibyte",
            "index":23,
            "blockchain":"dgb-testnet",
            "active":true
        },
        {
            "_id":"0018",
            "ticker":"DGB",
            "networkID":"mainnet",
            "network":"DGB-mainnet",
            "description":"",
            "index":24,
            "blockchain":"dgb-mainnet",
            "active":true
        },
        {
            "_id":"0019",
            "ticker":"DOGE",
            "networkID":"mainnet",
            "network":"DOGE-mainnet",
            "description":"",
            "index":25,
            "blockchain":"doge-mainnet",
            "active":true
        },
        {
            "_id":"001A",
            "ticker":"DOGE",
            "networkID":"mainnet",
            "network":"DOGE-mainnet",
            "description":"",
            "index":26,
            "blockchain":"doge-mainnet",
            "active":true
        },
        {
            "_id":"001B",
            "ticker":"EBST",
            "networkID":"mainnet",
            "network":"EBST-mainnet",
            "description":"Eboost",
            "index":27,
            "blockchain":"ebst",
            "active":true
        },
        {
            "_id":"001C",
            "ticker":"EOS",
            "networkID":"main",
            "network":"EOS-main",
            "description":"",
            "index":28,
            "blockchain":"eos-main",
            "active":true
        },
        {
            "_id":"001D",
            "ticker":"EOS",
            "networkID":"jungle",
            "network":"EOS-jungle",
            "description":"",
            "index":29,
            "blockchain":"eos-jungle",
            "active":true
        },
        {
            "_id":"001E",
            "ticker":"ETC",
            "networkID":"61",
            "network":"ETC-61",
            "description":"Mainnet",
            "index":30,
            "blockchain":"etc-mainnet",
            "active":true
        },
        {
            "_id":"001F",
            "ticker":"ETC",
            "networkID":"6",
            "network":"ETC-6",
            "description":"Kotti",
            "index":31,
            "blockchain":"etc-kotti",
            "active":true
        },
        {
            "_id":"0020",
            "ticker":"ETH",
            "networkID":"5",
            "network":"ETH-5",
            "description":"",
            "index":32,
            "blockchain":"eth-goerli",
            "active":true
        },
        {
            "_id":"0021",
            "ticker":"ETH",
            "networkID":"1",
            "network":"ETH-1",
            "description":"",
            "index":33,
            "blockchain":"eth-mainnet",
            "active":true
        },
        {
            "_id":"0022",
            "ticker":"ETH",
            "networkID":"4",
            "network":"ETH-4",
            "description":"",
            "index":34,
            "blockchain":"eth-rinkeby",
            "active":true
        },
        {
            "_id":"0023",
            "ticker":"ETH",
            "networkID":"3",
            "network":"ETH-3",
            "description":"",
            "index":35,
            "blockchain":"eth-ropsten",
            "active":true
        },
        {
            "_id":"0024",
            "ticker":"FIL",
            "networkID":"mainnet",
            "network":"FIL-mainnet",
            "description":"Filecoin Mainnet",
            "index":36,
            "blockchain":"fil-mainnet",
            "active":true
        },
        {
            "_id":"0025",
            "ticker":"FIL",
            "networkID":"testnet",
            "network":"FIL-testnet",
            "description":"Filecoin Testnet",
            "index":37,
            "blockchain":"fil-testnet",
            "active":true
        },
        {
            "_id":"0026",
            "ticker":"FLOW",
            "networkID":"mainnet",
            "network":"FLOW-mainnet",
            "description":"Flow",
            "index":38,
            "blockchain":"flow-mainnet",
            "active":true
        },
        {
            "_id":"0027",
            "ticker":"FLOW",
            "networkID":"testnet",
            "network":"FLOW-testnet",
            "description":"Flow",
            "index":39,
            "blockchain":"flow-testnet",
            "active":true
        },
        {
            "_id":"0028",
            "ticker":"FLOW",
            "networkID":"alpha",
            "network":"FLOW-alpha",
            "description":"Flow",
            "index":40,
            "blockchain":"flow-alpha",
            "active":true
        },
        {
            "_id":"0029",
            "ticker":"FTC",
            "networkID":"testnet",
            "network":"FTC-testnet",
            "description":"FeatherCoin",
            "index":41,
            "blockchain":"ftc-testnet",
            "active":true
        },
        {
            "_id":"002A",
            "ticker":"FTC",
            "networkID":"mainnet",
            "network":"FTC-mainnet",
            "description":"",
            "index":42,
            "blockchain":"ftc-mainnet",
            "active":true
        },
        {
            "_id":"002B",
            "ticker":"FTM",
            "networkID":"mainnet",
            "network":"FTM-mainnet",
            "description":"Fantom Mainnet",
            "index":43,
            "blockchain":"ftm-mainnet",
            "active":true
        },
        {
            "_id":"002C",
            "ticker":"FTM",
            "networkID":"testnet",
            "network":"FTM-testnet",
            "description":"Fantom Testnet",
            "index":44,
            "blockchain":"ftm-testnet",
            "active":true
        },
        {
            "_id":"002D",
            "ticker":"GRS",
            "networkID":"mainnet",
            "network":"GRS-mainnet",
            "description":"Groestlcoin",
            "index":45,
            "blockchain":"grs",
            "active":true
        },
        {
            "_id":"002E",
            "ticker":"HERC",
            "networkID":"mainnet",
            "network":"HERC-mainnet",
            "description":"Hercules",
            "index":46,
            "blockchain":"herc-mainnet",
            "active":true
        },
        {
            "_id":"002F",
            "ticker":"HOT",
            "networkID":"mainnet",
            "network":"HOT-mainnet",
            "description":"Holochain Mainnet",
            "index":47,
            "blockchain":"hot-mainnet",
            "active":true
        },
        {
            "_id":"0030",
            "ticker":"HOT",
            "networkID":"testnet",
            "network":"HOT-testnet",
            "description":"Holochain Testnet",
            "index":48,
            "blockchain":"hot-testnet",
            "active":true
        },
        {
            "_id":"0031",
            "ticker":"ICX",
            "networkID":"1",
            "network":"ICX-1",
            "description":"",
            "index":49,
            "blockchain":"icx-1",
            "active":true
        },
        {
            "_id":"0032",
            "ticker":"ICX",
            "networkID":"3",
            "network":"ICX-3",
            "description":"",
            "index":50,
            "blockchain":"icx-3",
            "active":true
        },
        {
            "_id":"0033",
            "ticker":"IND",
            "networkID":"mainnet",
            "network":"IND-mainnet",
            "description":"Indorse Token",
            "index":51,
            "blockchain":"ind-mainnet",
            "active":true
        },
        {
            "_id":"0034",
            "ticker":"IND",
            "networkID":"testnet",
            "network":"IND-testnet",
            "description":"",
            "index":52,
            "blockchain":"ind-testnet",
            "active":true
        },
        {
            "_id":"0035",
            "ticker":"LTC",
            "networkID":"testnet",
            "network":"LTC-testnet",
            "description":"",
            "index":53,
            "blockchain":"ltc-testnet",
            "active":true
        },
        {
            "_id":"0036",
            "ticker":"LTC",
            "networkID":"mainnet",
            "network":"LTC-mainnet",
            "description":"",
            "index":54,
            "blockchain":"ltc-mainnet",
            "active":true
        },
        {
            "_id":"0037",
            "ticker":"MATIC",
            "networkID":"mainnet",
            "network":"MATIC-mainnet",
            "description":"",
            "index":55,
            "blockchain":"matic-mainnet",
            "active":true
        },
        {
            "_id":"0038",
            "ticker":"BNB",
            "networkID":"mainnet",
            "network":"BNB-mainnet",
            "description":"Binance Chain",
            "index":56,
            "blockchain":"binance-mainnet",
            "active":true
        },
        {
            "_id":"0039",
            "ticker":"BNB",
            "networkID":"testnet",
            "network":"BNB-testnet",
            "description":"",
            "index":57,
            "blockchain":"binance-testnet",
            "active":true
        },
        {
            "_id":"003A",
            "ticker":"BNB",
            "networkID":"binance-chain-tigris(mainnet)",
            "network":"BNB-binance-chain-tigris(mainnet)",
            "description":"",
            "index":58,
            "blockchain":"binance-tigris",
            "active":true
        },
        {
            "_id":"003B",
            "ticker":"BNB",
            "networkID":"binance-chain-nile(testnet)",
            "network":"BNB-binance-chain-nile(testnet)",
            "description":"",
            "index":59,
            "blockchain":"binance-nile",
            "active":true
        },
        {
            "_id":"003C",
            "ticker":"NEO",
            "networkID":"mainnet",
            "network":"NEO-mainnet",
            "description":"NEO2 Mainnet",
            "index":60,
            "blockchain":"neo-mainnet",
            "active":true
        },
        {
            "_id":"003D",
            "ticker":"NEO",
            "networkID":"testnet",
            "network":"NEO-testnet",
            "description":"NEO2 Testnet",
            "index":61,
            "blockchain":"neo-testnet",
            "active":true
        },
        {
            "_id":"003E",
            "ticker":"PART",
            "networkID":"mainnet",
            "network":"PART-mainnet",
            "description":"",
            "index":62,
            "blockchain":"part-mainnet",
            "active":true
        },
        {
            "_id":"003F",
            "ticker":"PHT",
            "networkID":"162",
            "network":"PHT-162",
            "description":"",
            "index":63,
            "blockchain":"pht-162",
            "active":true
        },
        {
            "_id":"0040",
            "ticker":"PHT",
            "networkID":"163",
            "network":"PHT-163",
            "description":"",
            "index":64,
            "blockchain":"pht-163",
            "active":true
        },
        {
            "_id":"0041",
            "ticker":"PIVX",
            "networkID":"mainnet",
            "network":"PIVX-mainnet",
            "description":"",
            "index":65,
            "blockchain":"pivx-mainnet",
            "active":true
        },
        {
            "_id":"0042",
            "ticker":"POA",
            "networkID":"99",
            "network":"POA-99",
            "description":"POA Mainnet",
            "index":66,
            "blockchain":"poa-mainnet",
            "active":true
        },
        {
            "_id":"0043",
            "ticker":"POA",
            "networkID":"42",
            "network":"POA-42",
            "description":"POA Kovan",
            "index":67,
            "blockchain":"poa-kovan",
            "active":true
        },
        {
            "_id":"0044",
            "ticker":"POA",
            "networkID":"77",
            "network":"POA-77",
            "description":"POA Sokol",
            "index":68,
            "blockchain":"poa-sokol",
            "active":true
        },
        {
            "_id":"0045",
            "ticker":"POA",
            "networkID":"100",
            "network":"POA-100",
            "description":"POA xdai",
            "index":69,
            "blockchain":"poa-xdai",
            "active":true
        },
        {
            "_id":"0048",
            "ticker":"QTUM",
            "networkID":"mainnet",
            "network":"QTUM-mainnet",
            "description":"",
            "index":72,
            "blockchain":"qtum-mainnet",
            "active":true
        },
        {
            "_id":"0049",
            "ticker":"QTUM",
            "networkID":"testnet",
            "network":"QTUM-testnet",
            "description":"",
            "index":73,
            "blockchain":"qtum-testnet",
            "active":true
        },
        {
            "_id":"004A",
            "ticker":"REN",
            "networkID":"mainnet",
            "network":"REN-mainnet",
            "description":"",
            "index":74,
            "blockchain":"ren-mainnet",
            "active":true
        },
        {
            "_id":"004B",
            "ticker":"REN",
            "networkID":"testnet",
            "network":"REN-testnet",
            "description":"",
            "index":75,
            "blockchain":"ren-testnet",
            "active":true
        },
        {
            "_id":"004C",
            "ticker":"RSK",
            "networkID":"mainnet",
            "network":"RSK-mainnet",
            "description":"",
            "index":76,
            "blockchain":"rsk-mainnet",
            "active":true
        },
        {
            "_id":"004D",
            "ticker":"RSK",
            "networkID":"testnet",
            "network":"RSK-testnet",
            "description":"",
            "index":77,
            "blockchain":"rsk-testnet",
            "active":true
        },
        {
            "_id":"004E",
            "ticker":"RVN",
            "networkID":"testnet",
            "network":"RVN-testnet",
            "description":"Raven coin",
            "index":78,
            "blockchain":"rvn-testnet",
            "active":true
        },
        {
            "_id":"004F",
            "ticker":"RVN",
            "networkID":"mainnet",
            "network":"RVN-mainnet",
            "description":"",
            "index":79,
            "blockchain":"rvn-mainnet",
            "active":true
        },
        {
            "_id":"0050",
            "ticker":"SMART",
            "networkID":"testnet",
            "network":"SMART-testnet",
            "description":"",
            "index":80,
            "blockchain":"smart-testnet",
            "active":true
        },
        {
            "_id":"0051",
            "ticker":"SMART",
            "networkID":"mainnet",
            "network":"SMART-mainnet",
            "description":"",
            "index":81,
            "blockchain":"smart-mainnet",
            "active":true
        },
        {
            "_id":"0052",
            "ticker":"SOL",
            "networkID":"mainnet",
            "network":"SOL-mainnet",
            "description":"",
            "index":82,
            "blockchain":"sol-mainnet",
            "active":true
        },
        {
            "_id":"0053",
            "ticker":"SOL",
            "networkID":"mainnet-beta",
            "network":"SOL-mainnet-beta",
            "description":"",
            "index":83,
            "blockchain":"sol-mainnet-beta",
            "active":true
        },
        {
            "_id":"0054",
            "ticker":"SOL",
            "networkID":"testnet",
            "network":"SOL-testnet",
            "description":"",
            "index":84,
            "blockchain":"sol-testnet",
            "active":true
        },
        {
            "_id":"0055",
            "ticker":"SOL",
            "networkID":"devnet",
            "network":"SOL-devnet",
            "description":"",
            "index":85,
            "blockchain":"sol-devnet",
            "active":true
        },
        {
            "_id":"0056",
            "ticker":"TOMO",
            "networkID":"mainnet",
            "network":"TOMO-mainnet",
            "description":"",
            "index":86,
            "blockchain":"tomo-mainnet",
            "active":true
        },
        {
            "_id":"0057",
            "ticker":"TRX",
            "networkID":"mainnet",
            "network":"TRX-mainnet",
            "description":"",
            "index":87,
            "blockchain":"trx-mainnet",
            "active":true
        },
        {
            "_id":"0058",
            "ticker":"TRX",
            "networkID":"shasta",
            "network":"TRX-shasta",
            "description":"",
            "index":88,
            "blockchain":"trx-shasta",
            "active":true
        },
        {
            "_id":"0059",
            "ticker":"UFO",
            "networkID":"mainnet",
            "network":"UFO-mainnet",
            "description":"Unknown Fair Object",
            "index":89,
            "blockchain":"ufo-mainnet",
            "active":true
        },
        {
            "_id":"005A",
            "ticker":"VTC",
            "networkID":"mainnet",
            "network":"VTC-mainnet",
            "description":"Vertcoin",
            "index":90,
            "blockchain":"vtc-mainnet",
            "active":true
        },
        {
            "_id":"005B",
            "ticker":"WAVES",
            "networkID":"w",
            "network":"WAVES-w",
            "description":"",
            "index":91,
            "blockchain":"waves",
            "active":true
        },
        {
            "_id":"005C",
            "ticker":"XLM",
            "networkID":"testnet(horizon)",
            "network":"XLM-testnet(horizon)",
            "description":"",
            "index":92,
            "blockchain":"xlm-testnet",
            "active":true
        },
        {
            "_id":"005D",
            "ticker":"XLM",
            "networkID":"mainnet",
            "network":"XLM-mainnet",
            "description":"",
            "index":93,
            "blockchain":"xlm-mainnet",
            "active":true
        },
        {
            "_id":"005E",
            "ticker":"XMR",
            "networkID":"mainnet",
            "network":"XMR-mainnet",
            "description":"",
            "index":94,
            "blockchain":"xmr-mainnet",
            "active":true
        },
        {
            "_id":"005F",
            "ticker":"XMR",
            "networkID":"stagenet",
            "network":"XMR-stagenet",
            "description":"",
            "index":95,
            "blockchain":"xmr-stagenet",
            "active":true
        },
        {
            "_id":"0060",
            "ticker":"XMR",
            "networkID":"testnet",
            "network":"XMR-testnet",
            "description":"",
            "index":96,
            "blockchain":"xmr-testnet",
            "active":true
        },
        {
            "_id":"0061",
            "ticker":"XRP",
            "networkID":"devnet",
            "network":"XRP-devnet",
            "description":"",
            "index":97,
            "blockchain":"xrp-devnet",
            "active":true
        },
        {
            "_id":"0062",
            "ticker":"XRP",
            "networkID":"testnet",
            "network":"XRP-testnet",
            "description":"",
            "index":98,
            "blockchain":"xrp-testnet",
            "active":true
        },
        {
            "_id":"0063",
            "ticker":"XRP",
            "networkID":"mainnet",
            "network":"XRP-mainnet",
            "description":"",
            "index":99,
            "blockchain":"xrp-mainnet",
            "active":true
        },
        {
            "_id":"0064",
            "ticker":"XTZ",
            "networkID":"alphanet",
            "network":"XTZ-alphanet",
            "description":"",
            "index":100,
            "blockchain":"xtz-alphanet",
            "active":true
        },
        {
            "_id":"0065",
            "ticker":"XTZ",
            "networkID":"mainnet",
            "network":"XTZ-mainnet",
            "description":"",
            "index":101,
            "blockchain":"xtz-mainnet",
            "active":true
        },
        {
            "_id":"0066",
            "ticker":"XZC",
            "networkID":"mainnet",
            "network":"XZC-mainnet",
            "description":"",
            "index":102,
            "blockchain":"xzc-mainnet",
            "active":true
        },
        {
            "_id":"0067",
            "ticker":"XZC",
            "networkID":"mainnet",
            "network":"XZC-mainnet",
            "description":"zcoin",
            "index":103,
            "blockchain":"xzc-mainnet",
            "active":true
        },
        {
            "_id":"0068",
            "ticker":"XZC",
            "networkID":"testnet",
            "network":"XZC-testnet",
            "description":"",
            "index":104,
            "blockchain":"xzc-testnet",
            "active":true
        },
        {
            "_id":"0069",
            "ticker":"ZIL",
            "networkID":"mainnet",
            "network":"ZIL-mainnet",
            "description":"Ziliqa Mainnet",
            "index":105,
            "blockchain":"zil-mainnet",
            "active":true
        },
        {
            "_id":"006A",
            "ticker":"ZIL",
            "networkID":"devnet",
            "network":"ZIL-devnet",
            "description":"Ziliqua Testnet",
            "index":106,
            "blockchain":"zil-devnet",
            "active":true
        },
        {
            "_id":"006B",
            "ticker":"IPFS",
            "networkID":"mainnet",
            "network":"IPFS-mainnet",
            "description":"IPFS",
            "index":107,
            "blockchain":"ipfs-mainnet",
            "active":true
        },
        {
            "_id":"006C",
            "ticker":"MATIC",
            "networkID":"testnetV3",
            "network":"MATIC-testnetV3",
            "description":"",
            "index":108,
            "blockchain":"matic-testnetv3",
            "active":true
        },
        {
            "_id":"006D",
            "ticker":"MATIC",
            "networkID":"betanetV2",
            "network":"MATIC-betanetV2",
            "description":"",
            "index":109,
            "blockchain":"matic-betanetv2",
            "active":true
        }
    ]
    And each {_id}, {ticker}, {networkID}, {network}, {description}, {index}, {blockchain} and {active} matches the information displayed in the UI.

Scenario: Most Popular Chains visual verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then make sure to check the Most Popular Chains list, being present.
    And scroll all the way doen the list.
    And notice that the Network, Network ID, Hash, Description, Ticket and Index information are present. Example: 
    | POKT-mainnet | mainnet | 0001|   | POKT | 1 |

Scenario: Most Popular Chains verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then execute the following GET call: Example: 
    |https://api-testnet.dashboard.pokt.network:4200/api/network/chains|
    And receive the following response, that should have all of the information displayed in the UI:
    [
        {
            "_id":"0001",
            "ticker":"POKT",
            "networkID":"mainnet",
            "network":"POKT-mainnet",
            "description":"",
            "index":1,
            "blockchain":"mainnet",
            "active":true
        },
        {
            "_id":"0002",
            "ticker":"POKT",
            "networkID":"testnet",
            "network":"POKT-testnet",
            "description":"",
            "index":2,
            "blockchain":"testnet",
            "active":true
        },
        {
            "_id":"0003",
            "ticker":"AION",
            "networkID":"32",
            "network":"AION-32",
            "description":"",
            "index":3,
            "blockchain":"aion-32",
            "active":true
        },
        {
            "_id":"0004",
            "ticker":"AION",
            "networkID":"256",
            "network":"AION-256",
            "description":"",
            "index":4,
            "blockchain":"aion-256",
            "active":true
        },
        {
            "_id":"0005",
            "ticker":"ALGO",
            "networkID":"mainnet-v1.0",
            "network":"ALGO-mainnet-v1.0",
            "description":"",
            "index":5,
            "blockchain":"algo-mainnet",
            "active":true
        },
        {
            "_id":"0006",
            "ticker":"ALGO",
            "networkID":"testnet-v1.0",
            "network":"ALGO-testnet-v1.0",
            "description":"",
            "index":6,
            "blockchain":"algo-testnet",
            "active":true
        },
        {
            "_id":"0007",
            "ticker":"ALGO",
            "networkID":"betanet-v1.0",
            "network":"ALGO-betanet-v1.0",
            "description":"",
            "index":7,
            "blockchain":"algo-betanet",
            "active":true
        },
        {
            "_id":"0008",
            "ticker":"ANT",
            "networkID":"mainnet",
            "network":"ANT-mainnet",
            "description":"",
            "index":8,
            "blockchain":"ant-mainnet",
            "active":true
        },
        {
            "_id":"0009",
            "ticker":"ANT",
            "networkID":"testnet",
            "network":"ANT-testnet",
            "description":"",
            "index":9,
            "blockchain":"ant-testnet",
            "active":true
        },
        {
            "_id":"000A",
            "ticker":"AR",
            "networkID":"mainnet",
            "network":"AR-mainnet",
            "description":"Arweave Mainnet",
            "index":10,
            "blockchain":"ar-mainnet",
            "active":true
        },
        {
            "_id":"000B",
            "ticker":"BCH",
            "networkID":"mainnet",
            "network":"BCH-mainnet",
            "description":"",
            "index":11,
            "blockchain":"bch-mainnet",
            "active":true
        },
        {
            "_id":"000C",
            "ticker":"BCH",
            "networkID":"testnet",
            "network":"BCH-testnet",
            "description":"",
            "index":12,
            "blockchain":"bch-testnet",
            "active":true
        },
        {
            "_id":"000D",
            "ticker":"BSV",
            "networkID":"mainnet",
            "network":"BSV-mainnet",
            "description":"Bitcoin SV",
            "index":13,
            "blockchain":"bsv-mainnet",
            "active":true
        },
        {
            "_id":"000E",
            "ticker":"BSV",
            "networkID":"testnet",
            "network":"BSV-testnet",
            "description":"",
            "index":14,
            "blockchain":"bsv-testnet",
            "active":true
        },
        {
            "_id":"000F",
            "ticker":"BSV",
            "networkID":"stn",
            "network":"BSV-stn",
            "description":"",
            "index":15,
            "blockchain":"bsv-stn",
            "active":true
        },
        {
            "_id":"0010",
            "ticker":"BTC",
            "networkID":"mainnet",
            "network":"BTC-mainnet",
            "description":"",
            "index":16,
            "blockchain":"btc-mainnet",
            "active":true
        },
        {
            "_id":"0011",
            "ticker":"BTC",
            "networkID":"testnet",
            "network":"BTC-testnet",
            "description":"",
            "index":17,
            "blockchain":"btc-testnet",
            "active":true
        },
        {
            "_id":"0012",
            "ticker":"BTG",
            "networkID":"testnet",
            "network":"BTG-testnet",
            "description":"",
            "index":18,
            "blockchain":"btg-testnet",
            "active":true
        },
        {
            "_id":"0013",
            "ticker":"BTG",
            "networkID":"mainnet",
            "network":"BTG-mainnet",
            "description":"",
            "index":19,
            "blockchain":"btg-mainnet",
            "active":true
        },
        {
            "_id":"0014",
            "ticker":"DAPS",
            "networkID":"mainnet",
            "network":"DAPS-mainnet",
            "description":"",
            "index":20,
            "blockchain":"daps-mainnet",
            "active":true
        },
        {
            "_id":"0015",
            "ticker":"DASH",
            "networkID":"testnet",
            "network":"DASH-testnet",
            "description":"",
            "index":21,
            "blockchain":"dash-testnet",
            "active":true
        },
        {
            "_id":"0016",
            "ticker":"DASH",
            "networkID":"mainnet",
            "network":"DASH-mainnet",
            "description":"",
            "index":22,
            "blockchain":"dash-mainnet",
            "active":true
        },
        {
            "_id":"0017",
            "ticker":"DGB",
            "networkID":"testnet",
            "network":"DGB-testnet",
            "description":"digibyte",
            "index":23,
            "blockchain":"dgb-testnet",
            "active":true
        },
        {
            "_id":"0018",
            "ticker":"DGB",
            "networkID":"mainnet",
            "network":"DGB-mainnet",
            "description":"",
            "index":24,
            "blockchain":"dgb-mainnet",
            "active":true
        },
        {
            "_id":"0019",
            "ticker":"DOGE",
            "networkID":"mainnet",
            "network":"DOGE-mainnet",
            "description":"",
            "index":25,
            "blockchain":"doge-mainnet",
            "active":true
        },
        {
            "_id":"001A",
            "ticker":"DOGE",
            "networkID":"mainnet",
            "network":"DOGE-mainnet",
            "description":"",
            "index":26,
            "blockchain":"doge-mainnet",
            "active":true
        },
        {
            "_id":"001B",
            "ticker":"EBST",
            "networkID":"mainnet",
            "network":"EBST-mainnet",
            "description":"Eboost",
            "index":27,
            "blockchain":"ebst",
            "active":true
        },
        {
            "_id":"001C",
            "ticker":"EOS",
            "networkID":"main",
            "network":"EOS-main",
            "description":"",
            "index":28,
            "blockchain":"eos-main",
            "active":true
        },
        {
            "_id":"001D",
            "ticker":"EOS",
            "networkID":"jungle",
            "network":"EOS-jungle",
            "description":"",
            "index":29,
            "blockchain":"eos-jungle",
            "active":true
        },
        {
            "_id":"001E",
            "ticker":"ETC",
            "networkID":"61",
            "network":"ETC-61",
            "description":"Mainnet",
            "index":30,
            "blockchain":"etc-mainnet",
            "active":true
        },
        {
            "_id":"001F",
            "ticker":"ETC",
            "networkID":"6",
            "network":"ETC-6",
            "description":"Kotti",
            "index":31,
            "blockchain":"etc-kotti",
            "active":true
        },
        {
            "_id":"0020",
            "ticker":"ETH",
            "networkID":"5",
            "network":"ETH-5",
            "description":"",
            "index":32,
            "blockchain":"eth-goerli",
            "active":true
        },
        {
            "_id":"0021",
            "ticker":"ETH",
            "networkID":"1",
            "network":"ETH-1",
            "description":"",
            "index":33,
            "blockchain":"eth-mainnet",
            "active":true
        },
        {
            "_id":"0022",
            "ticker":"ETH",
            "networkID":"4",
            "network":"ETH-4",
            "description":"",
            "index":34,
            "blockchain":"eth-rinkeby",
            "active":true
        },
        {
            "_id":"0023",
            "ticker":"ETH",
            "networkID":"3",
            "network":"ETH-3",
            "description":"",
            "index":35,
            "blockchain":"eth-ropsten",
            "active":true
        },
        {
            "_id":"0024",
            "ticker":"FIL",
            "networkID":"mainnet",
            "network":"FIL-mainnet",
            "description":"Filecoin Mainnet",
            "index":36,
            "blockchain":"fil-mainnet",
            "active":true
        },
        {
            "_id":"0025",
            "ticker":"FIL",
            "networkID":"testnet",
            "network":"FIL-testnet",
            "description":"Filecoin Testnet",
            "index":37,
            "blockchain":"fil-testnet",
            "active":true
        },
        {
            "_id":"0026",
            "ticker":"FLOW",
            "networkID":"mainnet",
            "network":"FLOW-mainnet",
            "description":"Flow",
            "index":38,
            "blockchain":"flow-mainnet",
            "active":true
        },
        {
            "_id":"0027",
            "ticker":"FLOW",
            "networkID":"testnet",
            "network":"FLOW-testnet",
            "description":"Flow",
            "index":39,
            "blockchain":"flow-testnet",
            "active":true
        },
        {
            "_id":"0028",
            "ticker":"FLOW",
            "networkID":"alpha",
            "network":"FLOW-alpha",
            "description":"Flow",
            "index":40,
            "blockchain":"flow-alpha",
            "active":true
        },
        {
            "_id":"0029",
            "ticker":"FTC",
            "networkID":"testnet",
            "network":"FTC-testnet",
            "description":"FeatherCoin",
            "index":41,
            "blockchain":"ftc-testnet",
            "active":true
        },
        {
            "_id":"002A",
            "ticker":"FTC",
            "networkID":"mainnet",
            "network":"FTC-mainnet",
            "description":"",
            "index":42,
            "blockchain":"ftc-mainnet",
            "active":true
        },
        {
            "_id":"002B",
            "ticker":"FTM",
            "networkID":"mainnet",
            "network":"FTM-mainnet",
            "description":"Fantom Mainnet",
            "index":43,
            "blockchain":"ftm-mainnet",
            "active":true
        },
        {
            "_id":"002C",
            "ticker":"FTM",
            "networkID":"testnet",
            "network":"FTM-testnet",
            "description":"Fantom Testnet",
            "index":44,
            "blockchain":"ftm-testnet",
            "active":true
        },
        {
            "_id":"002D",
            "ticker":"GRS",
            "networkID":"mainnet",
            "network":"GRS-mainnet",
            "description":"Groestlcoin",
            "index":45,
            "blockchain":"grs",
            "active":true
        },
        {
            "_id":"002E",
            "ticker":"HERC",
            "networkID":"mainnet",
            "network":"HERC-mainnet",
            "description":"Hercules",
            "index":46,
            "blockchain":"herc-mainnet",
            "active":true
        },
        {
            "_id":"002F",
            "ticker":"HOT",
            "networkID":"mainnet",
            "network":"HOT-mainnet",
            "description":"Holochain Mainnet",
            "index":47,
            "blockchain":"hot-mainnet",
            "active":true
        },
        {
            "_id":"0030",
            "ticker":"HOT",
            "networkID":"testnet",
            "network":"HOT-testnet",
            "description":"Holochain Testnet",
            "index":48,
            "blockchain":"hot-testnet",
            "active":true
        },
        {
            "_id":"0031",
            "ticker":"ICX",
            "networkID":"1",
            "network":"ICX-1",
            "description":"",
            "index":49,
            "blockchain":"icx-1",
            "active":true
        },
        {
            "_id":"0032",
            "ticker":"ICX",
            "networkID":"3",
            "network":"ICX-3",
            "description":"",
            "index":50,
            "blockchain":"icx-3",
            "active":true
        },
        {
            "_id":"0033",
            "ticker":"IND",
            "networkID":"mainnet",
            "network":"IND-mainnet",
            "description":"Indorse Token",
            "index":51,
            "blockchain":"ind-mainnet",
            "active":true
        },
        {
            "_id":"0034",
            "ticker":"IND",
            "networkID":"testnet",
            "network":"IND-testnet",
            "description":"",
            "index":52,
            "blockchain":"ind-testnet",
            "active":true
        },
        {
            "_id":"0035",
            "ticker":"LTC",
            "networkID":"testnet",
            "network":"LTC-testnet",
            "description":"",
            "index":53,
            "blockchain":"ltc-testnet",
            "active":true
        },
        {
            "_id":"0036",
            "ticker":"LTC",
            "networkID":"mainnet",
            "network":"LTC-mainnet",
            "description":"",
            "index":54,
            "blockchain":"ltc-mainnet",
            "active":true
        },
        {
            "_id":"0037",
            "ticker":"MATIC",
            "networkID":"mainnet",
            "network":"MATIC-mainnet",
            "description":"",
            "index":55,
            "blockchain":"matic-mainnet",
            "active":true
        },
        {
            "_id":"0038",
            "ticker":"BNB",
            "networkID":"mainnet",
            "network":"BNB-mainnet",
            "description":"Binance Chain",
            "index":56,
            "blockchain":"binance-mainnet",
            "active":true
        },
        {
            "_id":"0039",
            "ticker":"BNB",
            "networkID":"testnet",
            "network":"BNB-testnet",
            "description":"",
            "index":57,
            "blockchain":"binance-testnet",
            "active":true
        },
        {
            "_id":"003A",
            "ticker":"BNB",
            "networkID":"binance-chain-tigris(mainnet)",
            "network":"BNB-binance-chain-tigris(mainnet)",
            "description":"",
            "index":58,
            "blockchain":"binance-tigris",
            "active":true
        },
        {
            "_id":"003B",
            "ticker":"BNB",
            "networkID":"binance-chain-nile(testnet)",
            "network":"BNB-binance-chain-nile(testnet)",
            "description":"",
            "index":59,
            "blockchain":"binance-nile",
            "active":true
        },
        {
            "_id":"003C",
            "ticker":"NEO",
            "networkID":"mainnet",
            "network":"NEO-mainnet",
            "description":"NEO2 Mainnet",
            "index":60,
            "blockchain":"neo-mainnet",
            "active":true
        },
        {
            "_id":"003D",
            "ticker":"NEO",
            "networkID":"testnet",
            "network":"NEO-testnet",
            "description":"NEO2 Testnet",
            "index":61,
            "blockchain":"neo-testnet",
            "active":true
        },
        {
            "_id":"003E",
            "ticker":"PART",
            "networkID":"mainnet",
            "network":"PART-mainnet",
            "description":"",
            "index":62,
            "blockchain":"part-mainnet",
            "active":true
        },
        {
            "_id":"003F",
            "ticker":"PHT",
            "networkID":"162",
            "network":"PHT-162",
            "description":"",
            "index":63,
            "blockchain":"pht-162",
            "active":true
        },
        {
            "_id":"0040",
            "ticker":"PHT",
            "networkID":"163",
            "network":"PHT-163",
            "description":"",
            "index":64,
            "blockchain":"pht-163",
            "active":true
        },
        {
            "_id":"0041",
            "ticker":"PIVX",
            "networkID":"mainnet",
            "network":"PIVX-mainnet",
            "description":"",
            "index":65,
            "blockchain":"pivx-mainnet",
            "active":true
        },
        {
            "_id":"0042",
            "ticker":"POA",
            "networkID":"99",
            "network":"POA-99",
            "description":"POA Mainnet",
            "index":66,
            "blockchain":"poa-mainnet",
            "active":true
        },
        {
            "_id":"0043",
            "ticker":"POA",
            "networkID":"42",
            "network":"POA-42",
            "description":"POA Kovan",
            "index":67,
            "blockchain":"poa-kovan",
            "active":true
        },
        {
            "_id":"0044",
            "ticker":"POA",
            "networkID":"77",
            "network":"POA-77",
            "description":"POA Sokol",
            "index":68,
            "blockchain":"poa-sokol",
            "active":true
        },
        {
            "_id":"0045",
            "ticker":"POA",
            "networkID":"100",
            "network":"POA-100",
            "description":"POA xdai",
            "index":69,
            "blockchain":"poa-xdai",
            "active":true
        },
        {
            "_id":"0048",
            "ticker":"QTUM",
            "networkID":"mainnet",
            "network":"QTUM-mainnet",
            "description":"",
            "index":72,
            "blockchain":"qtum-mainnet",
            "active":true
        },
        {
            "_id":"0049",
            "ticker":"QTUM",
            "networkID":"testnet",
            "network":"QTUM-testnet",
            "description":"",
            "index":73,
            "blockchain":"qtum-testnet",
            "active":true
        },
        {
            "_id":"004A",
            "ticker":"REN",
            "networkID":"mainnet",
            "network":"REN-mainnet",
            "description":"",
            "index":74,
            "blockchain":"ren-mainnet",
            "active":true
        },
        {
            "_id":"004B",
            "ticker":"REN",
            "networkID":"testnet",
            "network":"REN-testnet",
            "description":"",
            "index":75,
            "blockchain":"ren-testnet",
            "active":true
        },
        {
            "_id":"004C",
            "ticker":"RSK",
            "networkID":"mainnet",
            "network":"RSK-mainnet",
            "description":"",
            "index":76,
            "blockchain":"rsk-mainnet",
            "active":true
        },
        {
            "_id":"004D",
            "ticker":"RSK",
            "networkID":"testnet",
            "network":"RSK-testnet",
            "description":"",
            "index":77,
            "blockchain":"rsk-testnet",
            "active":true
        },
        {
            "_id":"004E",
            "ticker":"RVN",
            "networkID":"testnet",
            "network":"RVN-testnet",
            "description":"Raven coin",
            "index":78,
            "blockchain":"rvn-testnet",
            "active":true
        },
        {
            "_id":"004F",
            "ticker":"RVN",
            "networkID":"mainnet",
            "network":"RVN-mainnet",
            "description":"",
            "index":79,
            "blockchain":"rvn-mainnet",
            "active":true
        },
        {
            "_id":"0050",
            "ticker":"SMART",
            "networkID":"testnet",
            "network":"SMART-testnet",
            "description":"",
            "index":80,
            "blockchain":"smart-testnet",
            "active":true
        },
        {
            "_id":"0051",
            "ticker":"SMART",
            "networkID":"mainnet",
            "network":"SMART-mainnet",
            "description":"",
            "index":81,
            "blockchain":"smart-mainnet",
            "active":true
        },
        {
            "_id":"0052",
            "ticker":"SOL",
            "networkID":"mainnet",
            "network":"SOL-mainnet",
            "description":"",
            "index":82,
            "blockchain":"sol-mainnet",
            "active":true
        },
        {
            "_id":"0053",
            "ticker":"SOL",
            "networkID":"mainnet-beta",
            "network":"SOL-mainnet-beta",
            "description":"",
            "index":83,
            "blockchain":"sol-mainnet-beta",
            "active":true
        },
        {
            "_id":"0054",
            "ticker":"SOL",
            "networkID":"testnet",
            "network":"SOL-testnet",
            "description":"",
            "index":84,
            "blockchain":"sol-testnet",
            "active":true
        },
        {
            "_id":"0055",
            "ticker":"SOL",
            "networkID":"devnet",
            "network":"SOL-devnet",
            "description":"",
            "index":85,
            "blockchain":"sol-devnet",
            "active":true
        },
        {
            "_id":"0056",
            "ticker":"TOMO",
            "networkID":"mainnet",
            "network":"TOMO-mainnet",
            "description":"",
            "index":86,
            "blockchain":"tomo-mainnet",
            "active":true
        },
        {
            "_id":"0057",
            "ticker":"TRX",
            "networkID":"mainnet",
            "network":"TRX-mainnet",
            "description":"",
            "index":87,
            "blockchain":"trx-mainnet",
            "active":true
        },
        {
            "_id":"0058",
            "ticker":"TRX",
            "networkID":"shasta",
            "network":"TRX-shasta",
            "description":"",
            "index":88,
            "blockchain":"trx-shasta",
            "active":true
        },
        {
            "_id":"0059",
            "ticker":"UFO",
            "networkID":"mainnet",
            "network":"UFO-mainnet",
            "description":"Unknown Fair Object",
            "index":89,
            "blockchain":"ufo-mainnet",
            "active":true
        },
        {
            "_id":"005A",
            "ticker":"VTC",
            "networkID":"mainnet",
            "network":"VTC-mainnet",
            "description":"Vertcoin",
            "index":90,
            "blockchain":"vtc-mainnet",
            "active":true
        },
        {
            "_id":"005B",
            "ticker":"WAVES",
            "networkID":"w",
            "network":"WAVES-w",
            "description":"",
            "index":91,
            "blockchain":"waves",
            "active":true
        },
        {
            "_id":"005C",
            "ticker":"XLM",
            "networkID":"testnet(horizon)",
            "network":"XLM-testnet(horizon)",
            "description":"",
            "index":92,
            "blockchain":"xlm-testnet",
            "active":true
        },
        {
            "_id":"005D",
            "ticker":"XLM",
            "networkID":"mainnet",
            "network":"XLM-mainnet",
            "description":"",
            "index":93,
            "blockchain":"xlm-mainnet",
            "active":true
        },
        {
            "_id":"005E",
            "ticker":"XMR",
            "networkID":"mainnet",
            "network":"XMR-mainnet",
            "description":"",
            "index":94,
            "blockchain":"xmr-mainnet",
            "active":true
        },
        {
            "_id":"005F",
            "ticker":"XMR",
            "networkID":"stagenet",
            "network":"XMR-stagenet",
            "description":"",
            "index":95,
            "blockchain":"xmr-stagenet",
            "active":true
        },
        {
            "_id":"0060",
            "ticker":"XMR",
            "networkID":"testnet",
            "network":"XMR-testnet",
            "description":"",
            "index":96,
            "blockchain":"xmr-testnet",
            "active":true
        },
        {
            "_id":"0061",
            "ticker":"XRP",
            "networkID":"devnet",
            "network":"XRP-devnet",
            "description":"",
            "index":97,
            "blockchain":"xrp-devnet",
            "active":true
        },
        {
            "_id":"0062",
            "ticker":"XRP",
            "networkID":"testnet",
            "network":"XRP-testnet",
            "description":"",
            "index":98,
            "blockchain":"xrp-testnet",
            "active":true
        },
        {
            "_id":"0063",
            "ticker":"XRP",
            "networkID":"mainnet",
            "network":"XRP-mainnet",
            "description":"",
            "index":99,
            "blockchain":"xrp-mainnet",
            "active":true
        },
        {
            "_id":"0064",
            "ticker":"XTZ",
            "networkID":"alphanet",
            "network":"XTZ-alphanet",
            "description":"",
            "index":100,
            "blockchain":"xtz-alphanet",
            "active":true
        },
        {
            "_id":"0065",
            "ticker":"XTZ",
            "networkID":"mainnet",
            "network":"XTZ-mainnet",
            "description":"",
            "index":101,
            "blockchain":"xtz-mainnet",
            "active":true
        },
        {
            "_id":"0066",
            "ticker":"XZC",
            "networkID":"mainnet",
            "network":"XZC-mainnet",
            "description":"",
            "index":102,
            "blockchain":"xzc-mainnet",
            "active":true
        },
        {
            "_id":"0067",
            "ticker":"XZC",
            "networkID":"mainnet",
            "network":"XZC-mainnet",
            "description":"zcoin",
            "index":103,
            "blockchain":"xzc-mainnet",
            "active":true
        },
        {
            "_id":"0068",
            "ticker":"XZC",
            "networkID":"testnet",
            "network":"XZC-testnet",
            "description":"",
            "index":104,
            "blockchain":"xzc-testnet",
            "active":true
        },
        {
            "_id":"0069",
            "ticker":"ZIL",
            "networkID":"mainnet",
            "network":"ZIL-mainnet",
            "description":"Ziliqa Mainnet",
            "index":105,
            "blockchain":"zil-mainnet",
            "active":true
        },
        {
            "_id":"006A",
            "ticker":"ZIL",
            "networkID":"devnet",
            "network":"ZIL-devnet",
            "description":"Ziliqua Testnet",
            "index":106,
            "blockchain":"zil-devnet",
            "active":true
        },
        {
            "_id":"006B",
            "ticker":"IPFS",
            "networkID":"mainnet",
            "network":"IPFS-mainnet",
            "description":"IPFS",
            "index":107,
            "blockchain":"ipfs-mainnet",
            "active":true
        },
        {
            "_id":"006C",
            "ticker":"MATIC",
            "networkID":"testnetV3",
            "network":"MATIC-testnetV3",
            "description":"",
            "index":108,
            "blockchain":"matic-testnetv3",
            "active":true
        },
        {
            "_id":"006D",
            "ticker":"MATIC",
            "networkID":"betanetV2",
            "network":"MATIC-betanetV2",
            "description":"",
            "index":109,
            "blockchain":"matic-betanetv2",
            "active":true
        }
    ]
    And each {_id}, {ticker}, {networkID}, {network}, {description}, {index}, {blockchain} and {active} matches the information displayed in the UI.

Scenario: Tables expand/collapse verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then find the Registered Nodes table and click on the "^" icon to make the table collapse.
    And find the Registered Nodes table and click on the "v" icon to make the table expand again.
    Then find the Registered Apps table and click on the "^" icon to make the table collapse.
    And find the Registered Apps table and click on the "v" icon to make the table expand again.
    Then find the Supported Blockchains table and click on the "^" icon to make the table collapse.
    And find the Supported Blockchains table and click on the "v" icon to make the table expand again.
    Then find the Most Popular Chains table and click on the "^" icon to make the table collapse.
    And find the Most Popular Chains table and click on the "v" icon to make the table expand again.

Scenario: Scroll-bar marker verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then find the Registered Nodes table and scroll it down/up, making sure the marker moves accordingly.
    Then find the Registered Apps table and scroll it down/up, making sure the marker moves accordingly.
    Then find the Supported Blockchains table and scroll it down/up, making sure the marker moves accordingly.
    Then find the Most Popular Chains table and scroll it down/up, making sure the marker moves accordingly.

Scenario: Apps-dropdown, create APP verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then find the App's dropdown at the top-right.
    And clicks it.
    Then the dropdown opens up giving the options: Create | Import.
    When Create is clicked...
    Then user is taken to the App's creation form, under the following URL: 
    |https://dashboard.testnet.pokt.network/dashboard/apps/new|

Scenario: Apps-dropdown, import APP verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then find the App's dropdown at the top-right.
    And clicks it.
    Then the dropdown opens up giving the options: Create | Import.
    When Import is clicked...
    Then user is taken to the App's creation form, under the following URL: 
    | https://dashboard.testnet.pokt.network/dashboard/apps/import|

Scenario: Nodes-dropdown, create Node verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then find the Node's dropdown at the top-right.
    And clicks it.
    Then the dropdown opens up giving the options: Create | Import.
    When Create is clicked...
    Then user is taken to the Node's creation form, under the following URL: 
    |https://dashboard.testnet.pokt.network/dashboard/nodes/new|

Scenario: Nodess-dropdown, import Node verification
    Given that the user is in the Pocket Dashboard. Example: 
    |https://dashboard.testnet.pokt.network/dashboard|
    When the page is fully loaded.
    Then find the Node's dropdown at the top-right.
    And clicks it.
    Then the dropdown opens up giving the options: Create | Import.
    When Import is clicked...
    Then user is taken to the Node's creation form, under the following URL: 
    | https://dashboard.testnet.pokt.network/dashboard/nodes/import|